### ISSUE TITLE
Posting a full on article

### ISSUE THREAD

**Issue by sahanDissanayake** [darkwhispering/facebook-sdk-v4-codeigniter#1]
Hi @darkwhispering ,

Great work, are you using this anywhere on a production environment ? #justcurious

Also is there a way to post something like below

```javascript
$data['picture'] = "http://www.example.com/image.jpg";
$data['link'] = "http://www.example.com/";
$data['message'] = "Your message";
$data['caption'] = "Caption";
$data['description'] = "Description";

$this->facebook->publish_article($data);
```

Is there anything similar i could do ?

**Comment by darkwhispering** [comment]
I have used my code on multiple production projects, all from small to larger sites with large amount of traffic.

There is currently no method made for publishing a article to Facebook in my library. You are more then welcome to add it and make a pull request.

**Comment by darkwhispering** [comment]
With version 3.0.0-beta1 you have support for all, or at least most of the Facebook Graph methods.

If you would like to test it, you can find the code here: https://github.com/darkwhispering/facebook-sdk-v4-codeigniter/tree/fb-sdk-v5-develop
