### ISSUE TITLE
 Call to a member function logged_in() on a non-object

### ISSUE THREAD

**Issue by payamka** [darkwhispering/facebook-sdk-v4-codeigniter#10]
Hi
What is reason for below error:

Severity: Error
Message: Call to a member function logged_in() on a non-object

**Comment by darkwhispering** [comment]
Can you please give some more detailed information?
What version of CI?
What version of my library?
Did you try to do something specific or did you get this when activating the library?
and more...

Here is a general explanation to that type of PHP error: https://stackoverflow.com/questions/12769982/reference-what-does-this-error-mean-in-php/12769983#12769983

**Comment by 13BEYT** [comment]
Hi , I got the same error :
Message: Call to a member function logged_in() on a non-object

Version CI : v3
version of your library : v5
