### ISSUE TITLE
User's Date Of Birth

### ISSUE THREAD

**Issue by iamjinaal** [darkwhispering/facebook-sdk-v4-codeigniter#11]
Can anyone tell me what i should do to get users birth date from facebook in this library ?

I have wrote following code in facebook.php

$user = (new FacebookRequest($session, 'GET', '/me?fields=id,email,first_name,last_name,gender'))
                    ->execute()
                    ->getGraphObject()
                    ->asArray();

                // Get users permissions list
                $user['permissions'] = (new FacebookRequest($session, 'GET', '/me/?fields=user_birthday'))
                    ->execute()
                    ->getGraphObject()
                    ->asArray();

                // Return data
                return $this->response(200, 'success', $user);

This gives me following error.

Array
(
    [code] => 100
    [message] => (#100) Tried accessing nonexisting field (user_birthday) on node type (User)
    [data] => Array
        (
        )

)

**Comment by darkwhispering** [comment]
Hi,

To be able to get a users birthday you have to use the [user_birthday](https://developers.facebook.com/docs/facebook-login/permissions#reference-user_birthday) permission.

When you have done that you can use the `birthday` parameter to get the users birthday info.
