### ISSUE TITLE
The example of web_login cannot print user info

### ISSUE THREAD

**Issue by chenbingchn** [darkwhispering/facebook-sdk-v4-codeigniter#12]
Hi darkwhispering, recently I am using your Facebook library for Facebook PHP SDK v5 with Codeigniter 3, but I got a question. I run your example web_login, I got nothing of the user information. In fact, in the view of web.php, the $this->facebook->is_authenticated() didn't work. When I logged in or out my Facebook, it always showed Login but not the user information. In your example controller Example, I added a function test:

	public function test() {
		if($this->facebook->is_authenticated()) {
			echo "you are in";
		} else {
			echo "you are out";
		}
	}

when I run it, it always echo you are out.
I did everything your said but not configure the Session Variables. I keep it default. Is it the problem?
Thank you!

**Comment by darkwhispering** [comment]
Hi,

The Session Library must be configured correctly and working to be able to get a Facebook session correctly.

The Session Library, when activated defaults to the [Files Driver](http://www.codeigniter.com/user_guide/libraries/sessions.html#files-driver) for storing the sessions in a folder on your server. As a minimum you must configure the path to said folder or the session library will not work.

**Comment by MarcoTroost** [comment]
Hi Darkwhispering,

I'am experiencing the same problem as chenbingchn; i've kept the default session config variables, but after login, only the loginbutton is showed. After your advice i've added the following:

$config['sess_save_path'] = 'http://localhost:8888/application/sessions';

but still no userinfo & only the loginbutton shows. 
Any idea how i can fix this?

p.s. "sessions" is a folder with 777 read-write permissions (development)

kind regards, Marco

**Comment by AmitGairola** [comment]
Hi, I am using codeIgniter 3.0 and my session is configured to database table - ci_sessions as I am also tracking the user on the application by linking a session id to the user. 

How will this work with the Facebook class.

**Comment by darkwhispering** [comment]
Hi @chenbingchn @MarcoTroost @AmitGairola 

I have just committed a fix in the dev branch that should solve the issues of not getting the Facebook session, access token and user data after login in using the web redirect option.

Please update and test and let me know if it has solved your issues.

**Comment by TonyStark001** [comment]
hi @darkwhispering ,I just downloaded your facebook library. But still I'm redirected to login page i.e., $this->facebook->is_authenticated() returns empty.I've set session,facebook libraries in autoload.php.Please help :(

regards, Tony
