### ISSUE TITLE
Cannot get email from permission scope.

### ISSUE THREAD

**Issue by NichoTheMan** [darkwhispering/facebook-sdk-v4-codeigniter#14]
Hello, great job on this integration with codeigniter.

Everything is working except i can not seem to get additional user information other than the ID and the Full Name.

I just modified the way you fetched the user data in your example controller:

$user = $this->facebook->user();
if ($user['code'] === 200)
{
unset($user['data']['permissions']);
$data['user'] = $user['data'];
}

When i print $user i get this:
Array ( [code] => 200 [message] => success [data] => Array ( [name] => *NAME* [id] => *ID* ) );

I do not get email, which i also need for my application.

This is my facebook permissions in config:
$config['facebook_permissions']         = array('public_profile', 'email');

Am i doing something wrong or is this an issue with the library?

EDIT: When i print permissions aswell i get:
[permission] => email [status] => granted

**Comment by Xoshbin** [comment]
I have the same issue here, I can only grab the id and the full name. Others are all null like email , first name, gender etc, Thanks

**Comment by renjinsk** [comment]
you have to use graph api
`$this->facebook->request('get','/me?fields=email',$accessToken);`

**Comment by darkwhispering** [comment]
@Xoshbin @Xoshbin If you are using version 2.0.0 of the library you will have to manually modify the library source file.

Go to `application/libraries/Facebook.php` and on line `235` after `/me` add `?fields=email`. You can specify more fields like birthdate and such depending on the permission scopes you have. After modifying, it should look like `/me?fields=email`

If you are using version 3.0.0-beta1, than you need to do like mentioned by @renjinsk
