### ISSUE TITLE
multiple image upload 

### ISSUE THREAD

**Issue by damku999** [darkwhispering/facebook-sdk-v4-codeigniter#15]
hi brother thanks to for providing such this library it's easy to use but i want to share multiple images at time using-creating albums can you please help me for that.
this the not issue but my requierments

**Comment by darkwhispering** [comment]
As per Facebook Graph Documentation

> There is no way to publish more then one photo in the same graph API call.

You can read more here https://developers.facebook.com/docs/graph-api/reference/user/photos/#Creating
