### ISSUE TITLE
Problem with Facebook Request - Expired

### ISSUE THREAD

**Issue by raper1092** [darkwhispering/facebook-sdk-v4-codeigniter#17]
Hello,
At the beginning, thank you for your project "facebook-sdk-v4-codeigniter" and sorry for my English level but I hope you understand.

Everything worked fine until yesterday. 
My debug test

   print_r ($ this-> facebook-> user ());

When logging in get:
     [code] => 463
     [message] => Expired
     [date] => Array

I seek a on the internet and I found these articles:
https://www.sammyk.me/access-token-handling-best-practices-in-facebook-php-sdk-v4

https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension

It is described my problem may be related to the Access A token and its lifetime?
How repair this ?

Thank you in advance for your answer

**Comment by raper1092** [comment]
I used a newer version of the application . https://github.com/darkwhispering/facebook-sdk-v4-codeigniter/tree/fb-sdk-v5-develop
And what's interesting to me that only works in mozilla firefox. In other browsers I have the same problem . I would add that in application logs get:  
[FACEBOOK PHP SDK] code: 0 | message: Cross-site request forgery validation failed. The "state" param from the URL and session do not match.

**Comment by KWCG** [comment]
same problem stopped my app in this week. last week its was working

**Comment by darkwhispering** [comment]
@raper1092 @KWCG

**For library version 3.0.0**
I have just committed a update to the dev branch that fixes issues with the authentication and local session. Please update to latest, test and let me know.

**For library version 2.0.0**
Still looking into the issue

**Comment by KWCG** [comment]
fixed.

**Comment by darkwhispering** [comment]
Thanks for confirming
