### ISSUE TITLE
Bypass Config File?

### ISSUE THREAD

**Issue by renjinsk** [darkwhispering/facebook-sdk-v4-codeigniter#18]
Hi!
Is it possible to 'bypass' the config file?
I'm using multiple apps and i would like not to set the ID and Secret on a file but get it from database storage and change it.

I did try to leave it bank and/or use a "fake" one, then change it by `$this->config->set_item()`
but the lib didn't even let me to start.

**Comment by darkwhispering** [comment]
The library loads the config file on line `40` in `application/libraries/Facebook.php`.

Comment that out and load you config from the database in any way you would like. Remember to update the settings array in line `49-53` accordingly. That should do the trick.

**Comment by renjinsk** [comment]
I ended up with this... does the job, but... oh well..
`    public function __construct($args)
    {
        // Load config
        $this->load->config('facebook');

        // Load required libraries and helpers
        //$this->load->library('session');
        //$this->load->helper('url');

        // Initiate the Facebook SDK
        if (!isset($this->fb))
        {
            if(!$args)
            {
                $this->fb = new Facebook\Facebook([
                    'app_id' => $this->config->item('facebook_app_id'),
                    'app_secret' => $this->config->item('facebook_app_secret'),
                    'default_graph_version' => $this->config->item('facebook_graph_version')
                ]);
            }
            else
            {
                if(!isset($args['version']))
                {
                    $args['version'] = 'v2.5';
                }
                $this->fb = new Facebook\Facebook([
                    'app_id' => $args['app_id'],
                    'app_secret' => $args['app_secret'],
                    'default_graph_version' => $args['version']
                ]);
            }
        }
`
then i'm calling it with
`$args = array(
            'app_id' => 'APP_ID',
            'app_secret' => 'APP_SCRT',
            'version' => 'v2.5'
        );
        $this->load->library('facebook',$args);`

**Comment by darkwhispering** [comment]
That looks like a decent workaround. I'll consider maybe updating the library to support custom config in the future.
