### ISSUE TITLE
Email & other details not being passed with V2.5 of FB API

### ISSUE THREAD

**Issue by ralphioooo** [darkwhispering/facebook-sdk-v4-codeigniter#21]
Thanks for your hard work on this. I'm a little stuck with this now however. 

Had it all working on using an older FB app I had setup. Which is running V2.0 of the FB API.

Created a new FB app for production and it was given V2.5. When I login it only returns the persons name & ID... Nothing else is different that I can see.

Any idea's what is going wrong here?

Thanks

**Comment by ralphioooo** [comment]
Used the V5 branch and that solved the issue. But master definitely not working with V2.5 of FB api.

**Comment by renjinsk** [comment]
Yes, that's because master it for SDKv4 of FB and dev branch it's for the latest SDK version (v5)

**Comment by darkwhispering** [comment]
You have to use the beta version of the library if you use FB SDK v5 as mentioned by @renjinsk 

As soon as I tested and feel comfortable with the new version of the library it will replace the old version.
