### ISSUE TITLE
Facebook's src files not being included

### ISSUE THREAD

**Issue by ThatPixelDude** [darkwhispering/facebook-sdk-v4-codeigniter#23]
In the facebook.php file in libraries, we need to include the src files from fb sdk before we can use the facebook classes. This line needs to be added at the beginning.

require_once( APPPATH . 'vendor/facebook/php-sdk-v4/autoload.php' );

**Comment by darkwhispering** [comment]
@ThatPixelDude That is not needed if you activate Composer autoload in the [CodeIgniter config file](http://www.codeigniter.com/userguide3/general/autoloader.html?highlight=composer)

**Comment by ThatPixelDude** [comment]
I see. Thanks.

**Comment by nollyvenon** [comment]
I added it as stipulated but still get the same issue.
