### ISSUE TITLE
Session needs to be started in the library file

### ISSUE THREAD

**Issue by ThatPixelDude** [darkwhispering/facebook-sdk-v4-codeigniter#24]
session_start(); needs to be added in facebook.php in the libraries

**Comment by darkwhispering** [comment]
You don't need to add `session_start()`. The library loads the CodeIgniter Session Library it self if it is not already loaded. You need to make sure you have configured the Session Library correctly in `application/config/config.php`

Note: You should never use `session_start()` in CodeIgniter. Always use the [Session Library](http://www.codeigniter.com/userguide3/libraries/sessions.html)
