### ISSUE TITLE
Example controller works perfectly, other not

### ISSUE THREAD

**Issue by kivimango** [darkwhispering/facebook-sdk-v4-codeigniter#26]
Installed FB SDK for CI, Example controller works fine, when i want to load the library in other controller's constructor, it gives me a fatal error:
'Fatal error: Class 'CI_Facebook' not found in ...ci/system/core/Common.php on line 196'

When i edit the CI autoloader cfg to load the session library first, it says
'Unable to locate the specified class: Session.php'.
I copied the Session library to the application/libraries/ still getting the error.

Please provide me a fix, or help to solve the issue.

P.S.:
The system and app paths are set correctly in index.php.
On my home host it works, just FB doesnt allow login form the no-ip.org domains, so i uploaded it to a free host.

**Comment by kivimango** [comment]
Nvm, i solved it

**Comment by ruhinacse14** [comment]
Please reply how you solved it

**Comment by kivimango** [comment]
sorry, i dont remember, it was two years ago
