### ISSUE TITLE
No email in returned array

### ISSUE THREAD

**Issue by nacho004** [darkwhispering/facebook-sdk-v4-codeigniter#5]
Hello, first of all thank you very much for this library!

I have a problem when receiving data after login. Only shows me the name, id and granted permissions.

In the config/facebook.php file I put:
$config ['facebook_permissions'] = array ('public_profile', 'email');

But email is not being displayed at the output:

```
Array
(
    [code] => 200
    [message] => success
    [data] => Array
        (
            [name] => {MY_NAME}
            [id] => {MY_ID}
            [permissions] => Array
                (
                    [0] => stdClass Object
                        (
                            [permission] => email
                            [status] => granted
                        )

                    [1] => stdClass Object
                        (
                            [permission] => public_profile
                            [status] => granted
                        )

                )

        )

)
```

Thanks!

**Comment by tarunmangukiya** [comment]
Change the line 235 in Facebook.php with
`$user = (new FacebookRequest($session, 'GET', '/me?fields=id,name,email'))`

The use 
`$this->facebook->user();`
anywhere to get the user with email address.

**Comment by nacho004** [comment]
I did it and works fine! But I don't know if change the library code a good practice..

Thanks

**Comment by tarunmangukiya** [comment]
It may not be good practice, but I searched around on internet about it. So everyone suggested this...
________________________________

**Comment by nacho004** [comment]
Ok, thanks for your answer!



---
Ignacio Cuppi
Diseñador de Multimedios

Web: http://www.picatecla.com.ar
Perfil/Portfolio: http://ar.linkedin.com/in/icuppi
Blog: http://www.minyatur.com.ar

2015-09-01 13:38 GMT-03:00 Tarun Mangukiya <notifications@github.com>:

**Comment by darkwhispering** [comment]
The next major version update of the library will use a different approach in doing Graph API requests.

Instead of having multiple methods in the library, there is now one multipurpose method for all graph request, giving you as developer more freedom and options.

With new way of doing request you don't have to change the core of the library for this issue since you define the graph endpoint yourself.

Example:

```php
$user = $this->facebook->request('get', '/me?fields=name,email');
print_r($user);
```

You can test the beta version (v3.0.0-beta1) of the library now, code here https://github.com/darkwhispering/facebook-sdk-v4-codeigniter/tree/fb-sdk-v5-develop

**Comment by truongnguyenhd** [comment]
Fatal error: Class 'Facebook\Facebook' not found in F:\xampp\htdocs\codeigniter-3\application\libraries\Facebook.php on line 49

A PHP Error was encountered
Severity: Error
Message: Class 'Facebook\Facebook' not found
Filename: libraries/Facebook.php
Line Number: 49
Backtrace:


Help me!

**Comment by AmitGairola** [comment]
I also had a similar issue. I believe it is to do with the way FB SDK is installed. Solved it by copying the Facebook SDK from source file in the libraries and using a require_once 'Facebook/autoload.php' in the library.
