### ISSUE TITLE
Video post

### ISSUE THREAD

**Issue by cagdascakmakci** [darkwhispering/facebook-sdk-v4-codeigniter#8]
When I post video, I get error. 

this error = array(3) { ["code"]=> int(390) ["message"]=> string(64) "There was a problem uploading your video file. Please try again." ["data"]=> array(0) { } }

		$file = "domain/path/SampleVideo.mp4";
		
		$description = "First video";
		
		$title = "first video title";
				
		$resutl = $this->facebook->publish_video($file, $description, $title);

		if ($resutl) {
			var_dump($resutl);
		}else {
			echo "error";
		}

**Comment by darkwhispering** [comment]
The error is from Facebook, so it can be anything. Maybe incorrect file format, or the file size is to large or the encoding is not supported.

I would recommend looking into the Facebook documentation to see what the video graph endpoint support and not.
